# ----------------------------------------------------------------------
# rainbow, a terminal colorizer - https://github.com/nicoulaj/rainbow
# copyright (c) 2010-2018 rainbow contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------

sudo: false

language: python

cache: pip

matrix:
  include:
  - python: 2.7
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: 3.7
    dist: xenial
    sudo: true
  - python: 3.8-dev
    dist: xenial
    sudo: true
  - python: nightly
    dist: xenial
    sudo: true
  - python: pypy
  - python: pypy3
  allow_failures:
  - python: 3.8-dev
  - python: nightly

jobs:
  include:
    - stage: test
      script: tox
    - stage: lint
      script: tox -e lint
      python: 3.7
    - stage: benchmark
      script: tox -e benchmarks
      python: 3.7

install:
 - pip install tox-travis codeclimate-test-reporter

script: tox

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codeclimate-test-reporter

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: nicoulaj
  password:
    secure: "PH03sct2gKSxhfefRCNVYUqHGi5gPxBfMBe4ZIdNXR6WbfoLn/tOv1MkIasptABMHkhuSJ+Rr7o4GfsCXUmSuOPdMx9xsFhWyA/HBAeHRJpg4auDPUNIxGn89YJNVsWipJhL9vxjEXhuI1ySzaPR2KQ7wgYa6rfT9yGn34aQUBA="
  on:
    tags: true
    python: 3.7

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

notifications:
  email: false
  webhooks:
    urls: https://webhooks.gitter.im/e/3d9dabdef1a3d8b2ae8d
  irc:
    channels:
    - "chat.freenode.net#nicoulaj"
    on_success: never
    on_failure: change
    on_start: never
    use_notice: true
    template:
    - "%{repository}/%{branch}#%{build_number}: %{message} | changes : %{compare_url} | build : %{build_url}"
